# Makefile SE207

SYSTEMC   ?= /comelec/softs/opt/systemc-2.3.0
ARCH      = linux64

CPPFLAGS  =  -isystem $(SYSTEMC)/include
CXXFLAGS  =  -Wall -g
LDFLAGS   =  -L$(SYSTEMC)/lib-$(ARCH)
LDLIBS    =  -lsystemc


